# backend/app/services/ollama_service.py

import requests
import os
import logging
from typing import List, Dict, Optional, AsyncGenerator
import httpx
import json

logger = logging.getLogger(__name__)

class OllamaConnectionError(Exception):
    """Raised when we can't connect to Ollama"""
    pass

class OllamaService:
    """
    Handles all communication with Ollama.

    Design: Single responsibility = talk to Ollama API only.
    Doesn't know about conversations, databases, etc.
    """

    def __init__(self, base_url: Optional[str] = None):
        self.base_url = (
            base_url
            or os.getenv("OLLAMA_BASE_URL")
            or os.getenv("OLLAMA_URL", "http://host.docker.internal:11434")
        )
        self.timeout = 300  # 5 minutes for non-streaming requests

    async def generate_stream(
        self,
        model: str,
        prompt: str,
        system_prompt: Optional[str] = None,
        format_json: bool = False,
        options: Optional[dict] = None
    ) -> AsyncGenerator[str, None]:
        """Yields text tokens as they are generated by Ollama with optional slash command settings."""

        payload = {
            "model": model,
            "prompt": prompt,
            "stream": True
        }

        # Apply slash command options
        if system_prompt:
            payload["system"] = system_prompt

        if format_json:
            payload["format"] = "json"

        if options:
            payload["options"] = options

        # Configure granular timeouts so long prompt evaluations don't drop the connection
        stream_timeout = httpx.Timeout(
            connect=10.0,
            read=300.0,   # 5-minute read timeout between tokens for heavy prompt processing
            write=10.0,
            pool=10.0
        )

        try:
            async with httpx.AsyncClient(timeout=stream_timeout) as client:
                async with client.stream(
                    "POST",
                    f"{self.base_url}/api/generate",
                    json=payload
                ) as response:
                    if response.status_code != 200:
                        error_body = await response.aread()
                        logger.error(f"Ollama error status {response.status_code}: {error_body.decode()}")
                        yield f"Error from Ollama service: Status {response.status_code}"
                        return

                    async for line in response.aiter_lines():
                        if line:
                            try:
                                data = json.loads(line)
                                chunk = data.get("response", "")
                                if chunk:
                                    yield chunk
                            except json.JSONDecodeError:
                                continue

        except Exception as e:
            logger.error(f"Stream interrupted or failed: {type(e).__name__} - {e}")
            yield f"\n[Stream interrupted: {type(e).__name__}]"

    def _make_request(self, endpoint: str, method: str = "GET", json_data: Dict = None) -> Dict:
        """Helper method to make HTTP requests to Ollama."""
        url = f"{self.base_url}{endpoint}"

        try:
            logger.info(f"Ollama request: {method} {endpoint}")

            if method == "GET":
                response = requests.get(url, timeout=self.timeout)
            elif method == "POST":
                response = requests.post(url, json=json_data, timeout=self.timeout)
            else:
                raise ValueError(f"Unsupported method: {method}")

            response.raise_for_status()
            return response.json()

        except requests.ConnectionError:
            logger.error(f"Cannot connect to Ollama at {self.base_url}")
            raise OllamaConnectionError(f"Cannot connect to Ollama at {self.base_url}")
        except requests.Timeout:
            logger.error(f"Ollama request timed out after {self.timeout}s")
            raise OllamaConnectionError("Ollama request timed out")
        except requests.HTTPError as e:
            logger.error(f"Ollama returned error: {e}")
            raise OllamaConnectionError(f"Ollama error: {e}")

    def list_models(self) -> List[str]:
        """Get list of available models."""
        try:
            response = self._make_request("/api/tags")
            models = [model["name"] for model in response.get("models", [])]
            logger.info(f"Found {len(models)} models available")
            return models
        except OllamaConnectionError:
            raise
        except Exception as e:
            logger.error(f"Unexpected error listing models: {e}")
            raise OllamaConnectionError(f"Failed to list models: {e}")

    def generate(self, model: str, prompt: str, stream: bool = False) -> Dict:
        """Send prompt to model, get response."""
        try:
            logger.info(f"Generating with model={model}")

            response = self._make_request(
                "/api/generate",
                method="POST",
                json_data={
                    "model": model,
                    "prompt": prompt,
                    "stream": stream
                }
            )

            logger.info(f"Generation completed in {response.get('total_duration')}ms")
            return response

        except OllamaConnectionError:
            raise
        except Exception as e:
            logger.error(f"Error generating response: {e}")
            raise OllamaConnectionError(f"Generation failed: {e}")
